---
name: json-to-moonbit tests

on:  # yamllint disable-line rule:truthy
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - "master"
      - "main"
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run tests
        run: |
          node json-to-moonbit.test.js

      - name: Run json-to-moonbit using stdin
        shell: bash
        run: |
          set -eEuo pipefail
          got=$(node json-to-moonbit.js < tests/double-nested-objects.json)
          exp=$(cat tests/double-nested-objects.mbt)
          echo "got: '${got}'"
          [[ "${got}" == "${exp}" ]]

      - name: Run json-to-moonbit with a file
        shell: bash
        run: |
          set -eEuo pipefail
          got=$(node json-to-moonbit.js tests/double-nested-objects.json)
          exp=$(cat tests/double-nested-objects.mbt)
          echo "got: '${got}'"
          [[ "${got}" == "${exp}" ]]

      - name: Check correct error handling using stdin
        shell: bash
        run: |
          ! node json-to-moonbit.js <<< "error"

      - name: Check correct error handling with a file
        shell: bash
        run: |
          ! node json-to-moonbit.js <(echo "error")
